### PR TITLE
Centered Modal

### PR DESCRIPTION
**Pull request by phirephox**
#### What's this PR do?
- Fixes the position of the modal for the Live Dialog
#### Where should the reviewer start?
- At the Dialog > Live Section
#### How should this be manually tested?
- Click the dialog and check to see if the dialog is positioned correctly
#### What are the relevant tickets?
- Issue #80, TCFU-1604
#### Questions:
- Is there a blog post?
- Does the knowledge base need an update?
- Does this add new (Python) dependencies which need to be added to chef?

### CODE REVIEW

**Comment by r1teshkumar** [comment]
@phirephox , can you provide a screenshot from UI?

**Comment by phirephox** [comment]
image

**Comment by phirephox** [comment]
image

This is what it rendered as normally. This was requested and addressed because of it being behind the header at the top. It was fixed in this manner because putting it on top of the header doesn't look right and it should be centered to begin with.

**Comment by r1teshkumar** [comment]
@phirephox , the fix for something like this should be in the theme, not the style guide. Is this an issue iwth the theme?

**Comment by phirephox** [comment]
Checked the modal in the theme and the position is acting similar to this bug. Ticket needs to be revised to fix issue in theme.

**Pull request closed without merging**
